shell = "zsh"

# default apply defer
apply = ["defer"]

[templates]
defer = "{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}"

# non-deferred plugins
[plugins.zsh-defer]
github = "romkatv/zsh-defer"
apply = ["source"]

# deferred plugins
[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.zsh-syntax-highlighting]
github = "zdharma-continuum/fast-syntax-highlighting"

[plugins.user-completions]
local = "~/dotfiles/.zsh/Completion"
use = ["_gx"]
apply = ["fpath"]

[plugins.dotfiles-defer]
local = "~/dotfiles/zsh"
use = ["*.zsh"]

# inline plugins
[plugins.starship]
inline = 'eval "$(starship init zsh)"'

[plugins.direnv]
inline = 'eval "$(direnv hook zsh)"'

# https://github.com/rossmacarthur/sheldon/issues/114#issuecomment-731586665
# this plugin must last line
[plugins.compinit]
inline = 'autoload -Uz compinit && zsh-defer compinit'
