name: Test install

on: push

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 10
    steps:
    - name: Run install
      run: |
        sh -c "$(curl -fsLS get.chezmoi.io)" -- init --apply futabooo